services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./templates:/app
    environment:
      N8N_WEBHOOK_URL: "https://chileanrentacar.app.n8n.cloud/webhook/guardar-patente"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload